config/routes.rb
Rails.application.routes.draw do

  get "top/main"
  post "top/login"
  get "top/logout"
  
  resources :users
  resources :tweets
  resources :likes
  resources :profiles
  
  
  root "tweets#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  
  def like(user)
    likes.create(user_id: user.id)
  end
  
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def liked?(user) #いいね済みか調べる(true / false)
    like_users.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet
  has_one :profile, dependent: :destroy
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  
  helper_method :current_user
  private
    def current_user
      if session[:login_uid]
        User.find_by(uid: session[:login_uid])
      end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweet.like(current_user)
    end
    redirect_to root_path
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.liked?(current_user)
      tweet.unlike(current_user)
    end
    redirect_to root_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(message: params[:profile][:message])
    redirect_to tweets_path
  end
  
  def edit
    @profile = Profile.find(params[:id])
  end
  
  def show
    @profile = Profile.find(params[:id])
  end
  
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def main
    render "login_form"
  end
  
  def login
    
    user = User.find_by(uid: params[:uid])
    
    if user != nil and user.authenticate(params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to tweets_path
    else
      render "error", status: 442
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to tweets_path
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.new(message: params[:tweet][:message])
    @tweet.user = User.find_by(uid: current_user.uid)
    @tweet.save
    redirect_to tweets_path
  end
  
  def destroy
    @Tweet = Tweet.find(params[:id]).destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    u = User.new(uid: params[:user][:uid],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation])
    if User.find_by(uid: params[:user][:uid]) != nil
      flash[:notice] = "※ほかのユーザーとUIDが重複しています"
      redirect_to new_user_path
    else
      np = Profile.new(message: "")
      np.save
      u.profile = np
      u.save
      redirect_to top_main_path
    end
  end
  
  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "L5" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with model: @profile do |f| %>

  <%= f.label :message, "メッセージ" %><br>
  <%= f.text_area :message %><br>
  <%= f.submit "更新する" %>
<% end %>
<br>
<%= link_to 'プロフィールを見る', profile_path(@profile) %><br>
<%= link_to 'トップページに戻る', tweets_path %>

app/views/profiles/index.html.erb
<h1>全ユーザープロフィール一覧</h1>

<% @profiles.each do |e| %>
  -<br>
  ID：<%= e.user_id %><br>
  メッセージ：<%= e.message %><br>
  -
<% end %>
<br><br>
<%= link_to "ホームに戻る", tweets_path %>

app/views/profiles/show.html.erb
<h1>「<%= @profile.user.uid %>」のプロフィール</h1>

メッセージ：<%= @profile.message %><br><br>
<% if session[:login_uid] == @profile.user.uid %>
  <%= link_to "編集", edit_profile_path(@profile) %>
<% end %>
<%= link_to "戻る", :back %>

app/views/top/error.html.erb
<h1>ログイン失敗！</h1>
<%= link_to "戻る", :back %>

app/views/top/login_form.html.erb
<h1>ログイン</h1>

<%= form_with url: top_login_path, method: :post, local: true do |f| %>
  <%= f.label :uid, 'ユーザーID' %>
  <%= f.text_field :uid %>
  <%= f.label :pass, 'パスワード' %>
  <%= f.password_field :pass %>
  <%= f.submit 'ログイン' %>
<% end %>
<br>
<%= link_to "アカウント登録", new_user_path %>
<%= link_to "キャンセル", tweets_path %>

app/views/top/main.html.erb
<h1>トップページ</h1>

app/views/tweets/index.html.erb
<h1>ツイート一覧</h1>

ログイン中UID：<%= session[:login_uid] %><br>

<% u = User.find_by(uid: session[:login_uid] ) %>
<% if session[:login_uid] %>
  <%= link_to "マイプロフィールを表示", profile_path(u.profile) %><br>
<% end %>

<%= link_to "ログイン", top_main_path %><br>
<%= link_to "ログアウト", top_logout_path %><br><br>
<% @tweets.each do |e| %>
  <%= e.message %>
  いいね：<%= e.like_users.count %>件
  <%= link_to "削除", tweet_path(e), data: {turbo_method: :delete} %>
  
  <% if session[:login_uid] %>
    <br>
    <%= link_to 'いいね', likes_path(tweet_id: e.id), data: { turbo_method: :post } %>
    <%= link_to 'いいね削除', like_path(e), data: { turbo_method: :delete } %>
  <% end %>
  <br>
<% end %>
<br>
<% if session[:login_uid] %>
  <%= link_to "新規ツイート", new_tweet_path %>
<% end %>
<br><br>
<%= link_to "全ユーザープロファイル一覧", profiles_path %>
<%= link_to "全ユーザー一覧", users_path %>

app/views/tweets/new.html.erb
<h1>新規ツイート投稿</h1>

<%= form_with model: @tweet do |form| %>
  <%= form.label :message, "今何してる？" %>
  <%= form.text_field :message %>
  <br><br>
  <%= form.submit "投稿" %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% @users.each do |e| %>
  <p>uid: <%= e.uid %></p>
  <p>password_digest: <%= e.password_digest %></p>
  <%= link_to "プロフィールを表示", profile_path(e.profile) %>
  <%= link_to "削除", user_path(e), data: {turbo_method: :delete} %>
  <br>
<% end %>
<br>
<%= link_to "新規追加", new_user_path %>
<br>
<%= link_to "ホームに戻る", tweets_path %>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<%= form_with model: @user do |form| %>
  <p>
    <%= form.label :uid, "ユーザーID" %>
    <%= form.text_field :uid %>
  </p>
  <p>
    <%= form.label :password, "パスワード" %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation, 'パスワード(確認)' %>
    <%= form.text_field :password_confirmation %>
  </p>
  <%= form.submit "登録" %>
<% end %>
<br>
<%= link_to "キャンセル", tweets_path %>